global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'railway-prom'
    
scrape_configs:
  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-metrics.railway.internal:9187']
  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-metrics.railway.internal:9121']